//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBase.Infraestructura {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class StrCadenaConexion : global::System.Configuration.ApplicationSettingsBase {
        
        private static StrCadenaConexion defaultInstance = ((StrCadenaConexion)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StrCadenaConexion())));
        
        public static StrCadenaConexion Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]

        /// string de conexion de la base de datos a utilizar
        /// 


        //[global::System.Configuration.DefaultSettingValueAttribute("Data Source=SERVIDOR;Initial Catalog=BdSolucionesmi;User ID=sa;password=sa")]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=LocalHost; user id=postgres; Password=Seguridad2022; Database=postgres")]
        public string Cadena
        {
            get
            {
                return ((string)(this["Cadena"]));
            }
        }
    }
}
